name: Delete Multidev on Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-multidev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up PHP and Terminus
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # You can adjust the PHP version if needed
          tools: terminus
          extensions: mbstring, dom, filter, gd, iconv, json, Phar, session, simplexml, tokenizer, xml, zip # Common extensions for PHP tools

      - name: Authenticate Terminus and Install Secrets Plugin
        env:
          TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
        run: |
          terminus --version # Output Terminus version for debugging
          terminus auth:login --machine-token="$TERMINUS_TOKEN"
          terminus self:plugin:install pantheon-systems/terminus-secrets-plugin --yes

      - name: Delete Multidev Environment
        env:
          # TERMINUS_TOKEN is used in the auth step above
          # IMPORTANT: Ensure PANTHEON_SITE is set in GitHub repo variables
          PANTHEON_SITE: "${{ vars.PANTHEON_SITE || 'your-site-name' }}"
          # Get branch name from PR event
          BRANCH: "${{ github.event.pull_request.head.ref || github.head_ref || github.ref_name }}"
        run: |
          echo "Original branch name: $BRANCH"
          # Clean up branch name to be a valid multidev name (lowercase, alphanumeric, hyphens, max 11 chars, no leading/trailing hyphens)
          CLEAN_BRANCH=$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/^-*//;s/-*$//' | cut -c 1-11)
          echo "Cleaned branch name for multidev: ${CLEAN_BRANCH}"
          echo "Target Pantheon site: ${PANTHEON_SITE}"

          # Check if the multidev environment exists
          if terminus env:list "${PANTHEON_SITE}" --field=id | grep -qw "${CLEAN_BRANCH}"; then
            echo "Multidev environment '${CLEAN_BRANCH}' found for site '${PANTHEON_SITE}'. Deleting..."
            terminus env:delete "${PANTHEON_SITE}.${CLEAN_BRANCH}" --delete-branch --yes --force
            echo "Deletion command executed for multidev '${CLEAN_BRANCH}'."
          else
            echo "No multidev environment named '${CLEAN_BRANCH}' found for site '${PANTHEON_SITE}'. Nothing to delete."
          fi

      - name: Post cleanup comment
        uses: actions/github-script@v6
        if: always()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const hasExistingComment = comments.some(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.includes('Multidev environment cleanup')
            );
            
            if (!hasExistingComment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: 'Multidev environment cleanup completed.'
              });
            }
