name: PR Comments to Jira

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  process_pr_to_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira issue key from PR title
        id: extract_from_title
        run: echo "ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -o '[A-Z]\+-[0-9]\+' || echo "")" >> $GITHUB_OUTPUT

      - name: Extract Jira issue key from PR body
        id: extract_from_body
        if: steps.extract_from_title.outputs.ISSUE_KEY == ''
        run: echo "ISSUE_KEY=$(echo "${{ github.event.pull_request.body }}" | grep -o '[A-Z]\+-[0-9]\+' | head -1 || echo "")" >> $GITHUB_OUTPUT

      - name: Extract Jira issue key from branch name
        id: extract_from_branch
        if: steps.extract_from_title.outputs.ISSUE_KEY == '' && steps.extract_from_body.outputs.ISSUE_KEY == ''
        run: echo "ISSUE_KEY=$(echo "${{ github.head_ref || github.ref_name }}" | grep -o '[A-Z]\+-[0-9]\+' | head -1 || echo "")" >> $GITHUB_OUTPUT

      - name: Set final issue key
        id: set_issue_key
        run: echo "ISSUE_KEY=${{ steps.extract_from_title.outputs.ISSUE_KEY || steps.extract_from_body.outputs.ISSUE_KEY || steps.extract_from_branch.outputs.ISSUE_KEY }}" >> $GITHUB_OUTPUT

      - name: Post to Jira
        if: steps.set_issue_key.outputs.ISSUE_KEY != ''
        uses: atlassian/gajira-comment@master
        with:
          issue: ${{ steps.set_issue_key.outputs.ISSUE_KEY }}
          comment: |
            PR: "${{ github.event.pull_request.title }}" - ${{ github.event.pull_request.html_url }}
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
